'use client';
import {useState} from 'react';
import {LockKeyhole,ShieldCheck,Save} from 'lucide-react';
import type {SecurityPolicy} from '@/lib/eassist/types';
export default function Security({policy,save,busy}:{policy:SecurityPolicy;save:(policy:SecurityPolicy)=>Promise<void>;busy:boolean}){
  const [draft,setDraft]=useState(policy);
  const dirty=JSON.stringify(policy)!==JSON.stringify(draft);
  const options:[keyof Omit<SecurityPolicy,'max_concurrent'>,string,string][]=[
    ['require_https','Require HTTPS','Block integration requests over unencrypted HTTP.'],
    ['allow_writes','Allow source-system changes','Permit incident updates, silence changes, and automation configuration changes.'],
    ['allow_deletes','Allow source-system deletion','Permit deleting source records after a separate confirmation. Disabled by default.'],
    ['allow_runs','Allow task launches','Permit executing task templates in the connected automation runner.'],
    ['require_confirmation','Confirm every task launch','Require a short-lived, single-use launch confirmation before execution.'],
  ];
  return <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="ea-card"><div className="ea-toolbar"><ShieldCheck size={18}/><h2>Security configurations</h2></div><div className="p-5"><p className="ea-subtitle mb-5">These controls apply to your eAssist workspace and are enforced by the server for every operation. Permissions in each connected source system still apply.</p>{options.map(([key,label,description])=><label key={key} className="flex items-start gap-4 border-t border-slate-100 py-4"><div className="flex-1"><strong className="text-xs">{label}</strong><p className="ea-subtitle">{description}</p></div><input aria-label={label} type="checkbox" className="mt-1 size-4 accent-indigo-600" checked={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/></label>)}<label className="ea-label border-t border-slate-100 pt-4">Maximum concurrent runs<input className="ea-input max-w-32" type="number" min="1" max="20" value={draft.max_concurrent} onChange={e=>setDraft({...draft,max_concurrent:Number(e.target.value)})}/><span className="ea-subtitle">Active tasks and pending or uncertain launches count toward this limit.</span></label></div>{dirty&&<div className="ea-modal-foot"><button className="ea-btn" onClick={()=>setDraft(policy)}>Discard changes</button><button className="ea-btn ea-primary" disabled={busy} onClick={()=>void save(draft)}><Save size={14}/>Save security settings</button></div>}</section><div className="space-y-5"><section className="ea-card p-5"><LockKeyhole className="mb-4 text-indigo-500" size={24}/><h2>Credential protection</h2><p className="ea-subtitle">Integration credentials are encrypted at rest and used only by the server. Saved secret values are never returned to the browser. Webhook tokens are displayed only when generated.</p></section><section className="ea-card p-5"><h2>Connection boundaries</h2><p className="ea-subtitle">Only origins explicitly allowed in the server’s EASSIST_ALLOWED_ORIGINS setting can be contacted. Redirects are blocked. Every record and API request is scoped to the signed-in account.</p></section><section className="ea-card p-5"><h2>Audit and execution</h2><p className="ea-subtitle">The Activity page records security changes and operational actions. Duplicate launch submissions reuse the recorded result. Uncertain launch outcomes require reconciliation before another launch of the same template.</p></section></div></div>;
}
